mindie-service:
  tensor_parallel_size: 1
  pipeline_parallel_size: 1
  max_num_seqs: 256
  max_model_len: 28672
  max_num_batched_tokens: 28672
  max_seq_len_to_capture: 28672
  gpu_memory_utilization: 0.9
  block_size: 32
  swap_space: 0
  scheduling_policy: fcfs
engine_type: mindie-service
model: MindSDK/Qwen2.5-3B-Instruct
