mindie-service:
  tensor_parallel_size: 2
  pipeline_parallel_size: 1
  distributed_executor_backend: mp
  max_num_seqs: 64
  max_model_len: 21504
  max_num_batched_tokens: 21504
  max_seq_len_to_capture: 21504
  gpu_memory_utilization: 0.95
  block_size: 128
  swap_space: 32
  scheduling_policy: fcfs
  quantization: ms-model-slim
  npu_memory_fraction: 0.95
engine_type: mindie-service
model: MindSDK/QwQ-32B-w8a8
