mindie-service:
  tensor_parallel_size: 8
  pipeline_parallel_size: 1
  distributed_executor_backend: mp
  max_num_seqs: 48
  max_model_len: 21504
  max_num_batched_tokens: 21504
  max_seq_len_to_capture: 21504
  gpu_memory_utilization: 0.9
  block_size: 128
  swap_space: 32
  scheduling_policy: fcfs
engine_type: mindie-service
model: MindSDK/DeepSeek-R1-Distill-Llama-70B
