# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# global arguments
global:
  # This is for the namespace
  namespace: mis

  # This is the ai server, currently support 800I A2
  aiServer: 800I A2

# for front end
frontend:
  # Application name
  appName: openwebui

  # This will set the replicaset count
  replicaCount: 1

  # This sets the container image
  image:
    image: ghcr.io/open-webui/open-webui:main
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent

  # This sets the resources for the front end
  resources:
    requests:
      memory: "32Gi"
    limits:
      memory: "32Gi"

  # This is for setting up a service
  service:
    # This sets the service type
    type: NodePort
    # This sets the ports
    port: 30000  # 30000-32767

# for Large Language Models
llm:
  # This is the model name
  modelName: deepseek-r1-distill-qwen-1.5b

  # This will set the replicaset count
  replicaCount: 1

  # This is the npu(accelerator) card number
  acceleratorCards: 1

  # This sets the container image
  image:
    repository: swr.cn-south-1.myhuaweicloud.com/ascendhub
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.1-arm64"

  # This is for the secrets for pulling an image from a private repository
  imagePullSecrets: []

  # This is for setting up a service
  service:
    # This sets the service type
    type: ClusterIP
    # This sets the ports
    port: 8000

  # Additional volumes on the output Deployment definition.
  volumes:
    - name: model
      nfs:
        path: /home/nfs/data/model
        server: 10.169.68.79