mindie-service:
  tensor_parallel_size: 2
  pipeline_parallel_size: 1
  distributed_executor_backend: mp
  max_num_seqs: 128
  max_model_len: 14336
  max_num_batched_tokens: 14336
  max_seq_len_to_capture: 14336
  gpu_memory_utilization: 0.9
  block_size: 32
  swap_space: 4
  scheduling_policy: fcfs
  npu_memory_fraction: 0.7
engine_type: mindie-service
model: MindSDK/MiniCPM-V-2_6
model_type: VLM
trust_remote_code: true
