mindie-service:
  tensor_parallel_size: 2
  pipeline_parallel_size: 1
  distributed_executor_backend: mp
  max_num_seqs: 128
  max_model_len: 14336
  max_num_batched_tokens: 14336
  max_seq_len_to_capture: 14336
  gpu_memory_utilization: 0.9
  block_size: 32
  swap_space: 8
  scheduling_policy: fcfs
  quantization: ms-model-slim
engine_type: mindie-service
model: MindSDK/DeepSeek-R1-Distill-Qwen-32B-w8a8
