mindie-service:
  tensor_parallel_size: 4
  pipeline_parallel_size: 1
  max_num_seqs: 64
  max_model_len: 250000
  max_num_batched_tokens: 250000
  max_seq_len_to_capture: 250000
  gpu_memory_utilization: 0.95
  block_size: 128
  swap_space: 8
  scheduling_policy: fcfs
engine_type: mindie-service
model: MindSDK/Qwen2.5-7B-Instruct-1M
