mindie-service:
  tensor_parallel_size: 2
  pipeline_parallel_size: 1
  max_num_seqs: 128
  max_model_len: 28000
  max_num_batched_tokens: 28000
  max_seq_len_to_capture: 28000
  gpu_memory_utilization: 0.9
  block_size: 32
  swap_space: 4
  scheduling_policy: fcfs
engine_type: mindie-service
model: MindSDK/Qwen2.5-VL-3B-Instruct
model_type: VLM
