mindie-service:
  tensor_parallel_size: 4
  pipeline_parallel_size: 1
  distributed_executor_backend: mp
  max_num_seqs: 256
  max_model_len: 32768
  max_num_batched_tokens: 32768
  max_seq_len_to_capture: 16384
  gpu_memory_utilization: 0.95
  block_size: 16
  swap_space: 4
  scheduling_policy: priority
  num_scheduler_steps: 1
engine_type: mindie-service
model: MindSDK/Qwen2.5-14B-Instruct
