vllm:
  dtype: bfloat16
  tensor_parallel_size: 8
  pipeline_parallel_size: 1
  max_num_seqs: 128
  max_model_len: 220000
  max_num_batched_tokens: 220000
  max_seq_len_to_capture: 220000
  gpu_memory_utilization: 0.9
  block_size: 32
  swap_space: 4
  cpu_offload_gb: 0
  scheduling_policy: fcfs
  enforce_eager: true
engine_type: vllm
model: MindSDK/Qwen2.5-14B-Instruct-1M
