mindie-service:
  tensor_parallel_size: 8
  pipeline_parallel_size: 1
  max_num_seqs: 64
  max_model_len: 220000
  max_num_batched_tokens: 220000
  max_seq_len_to_capture: 220000
  gpu_memory_utilization: 0.95
  block_size: 128
  swap_space: 8
  scheduling_policy: fcfs
engine_type: mindie-service
model: MindSDK/Qwen2.5-14B-Instruct-1M
