vllm:
  dtype: bfloat16
  tensor_parallel_size: 1
  pipeline_parallel_size: 1
  max_num_seqs: 64
  gpu_memory_utilization: 0.95
  block_size: 128
  swap_space: 0
  cpu_offload_gb: 0
  scheduling_policy: fcfs
  disable_async_output_proc: false
  multi_step_stream_outputs: true
  enable_chunked_prefill: true
  enable_prefix_caching: true
  enforce_eager: false
  quantization: compressed-tensors
engine_type: vllm
model: MindSDK/DeepSeek-R1-Distill-Qwen-1.5B-quantized.w8a8
