mindie-service:
  tensor_parallel_size: 1
  pipeline_parallel_size: 1
  max_num_seqs: 256
  max_model_len: 14336
  max_num_batched_tokens: 14336
  max_seq_len_to_capture: 7168
  gpu_memory_utilization: 0.95
  block_size: 16
  swap_space: 0
  scheduling_policy: priority
  num_scheduler_steps: 1
  quantization: ms-model-slim
engine_type: mindie-service
model: MindSDK/DeepSeek-R1-Distill-Qwen-1.5B-w8a8
