vllm:
  dtype: bfloat16
  tensor_parallel_size: 8
  pipeline_parallel_size: 1
  max_num_seqs: 128
  max_model_len: 21504
  max_num_batched_tokens: 21504
  max_seq_len_to_capture: 21504
  gpu_memory_utilization: 0.9
  block_size: 128
  swap_space: 8
  cpu_offload_gb: 0
  scheduling_policy: fcfs
engine_type: vllm
model: MindSDK/Qwen2.5-VL-32B-Instruct
model_type: VLM
