mindie-service:
  tensor_parallel_size: 4
  pipeline_parallel_size: 1
  max_num_seqs: 64
  max_model_len: 40960
  max_num_batched_tokens: 40960
  max_seq_len_to_capture: 40960
  gpu_memory_utilization: 0.9
  block_size: 128
  swap_space: 32
  scheduling_policy: fcfs
engine_type: mindie-service
model: MindSDK/Qwen2.5-VL-32B-Instruct
model_type: VLM
