mindie-service:
  tensor_parallel_size: 4
  pipeline_parallel_size: 1
  max_num_seqs: 128
  max_model_len: 36864
  max_num_batched_tokens: 36864
  max_seq_len_to_capture: 36864
  gpu_memory_utilization: 0.9
  block_size: 32
  swap_space: 8
  scheduling_policy: fcfs
engine_type: mindie-service
model: MindSDK/Qwen2.5-VL-32B-Instruct
model_type: VLM
