mindie-service:
  tensor_parallel_size: 2
  pipeline_parallel_size: 1
  distributed_executor_backend: mp
  max_num_seqs: 256
  max_model_len: 10500
  max_num_batched_tokens: 14336
  max_seq_len_to_capture: 7168
  gpu_memory_utilization: 0.95
  block_size: 16
  swap_space: 4
  scheduling_policy: priority
  num_scheduler_steps: 1
engine_type: mindie-service
model: MindSDK/DeepSeek-R1-Distill-Qwen-14B
