mindie-service:
  tensor_parallel_size: 2
  pipeline_parallel_size: 1
  max_num_seqs: 64
  max_model_len: 21504
  max_num_batched_tokens: 21504
  max_seq_len_to_capture: 21504
  gpu_memory_utilization: 0.95
  block_size: 128
  swap_space: 8
  scheduling_policy: fcfs
  enable_prefix_caching: true
engine_type: mindie-service
model: MindSDK/Qwen2.5-7B-Instruct
