mindie-service:
  tensor_parallel_size: 1
  pipeline_parallel_size: 1
  max_num_seqs: 64
  gpu_memory_utilization: 0.95
  block_size: 128
  swap_space: 0
  scheduling_policy: fcfs
engine_type: mindie-service
model: MindSDK/Llama-3.2-1B-Instruct
