optimal_engine_type: vllm
vllm:
  dtype: bfloat16
  tensor_parallel_size: 1
  pipeline_parallel_size: 1
  max_num_seqs: 256
  max_model_len: 32768
  max_num_batched_tokens: 32768
  max_seq_len_to_capture: 32768
  gpu_memory_utilization: 0.9
  block_size: 32
  swap_space: 0
  cpu_offload_gb: 0
  scheduling_policy: fcfs
  enforce_eager: true
mindie: {}
