vllm:
  dtype: bfloat16
  tensor_parallel_size: 2
  pipeline_parallel_size: 1
  distributed_executor_backend: mp
  max_num_seqs: 64
  max_model_len: 24576
  max_num_batched_tokens: 24576
  max_seq_len_to_capture: 24576
  gpu_memory_utilization: 0.9
  block_size: 128
  swap_space: 32
  cpu_offload_gb: 0
  scheduling_policy: fcfs
  disable_async_output_proc: false
  multi_step_stream_outputs: true
  enable_chunked_prefill: false
  enable_prefix_caching: false
  enforce_eager: true
  quantization: compressed-tensors
engine_type: vllm
model: MindSDK/DeepSeek-R1-Distill-Qwen-32B-quantized.w8a8
