vllm:
  dtype: bfloat16
  tensor_parallel_size: 8
  pipeline_parallel_size: 1
  max_num_seqs: 48
  max_model_len: 24576
  max_num_batched_tokens: 24576
  max_seq_len_to_capture: 24576
  gpu_memory_utilization: 0.9
  block_size: 128
  swap_space: 32
  cpu_offload_gb: 0
  scheduling_policy: fcfs
  disable_async_output_proc: false
  multi_step_stream_outputs: true
  enable_chunked_prefill: false
  enable_prefix_caching: false
  enforce_eager: true
engine_type: vllm
model: MindSDK/Llama-3.3-70B-Instruct
